package com.example.bsproperty.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bsproperty.bean.UserBean;
import com.example.bsproperty.bean.ShareBean;
import com.example.bsproperty.bean.SportsBean;

import com.example.bsproperty.greendao.UserBeanDao;
import com.example.bsproperty.greendao.ShareBeanDao;
import com.example.bsproperty.greendao.SportsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig shareBeanDaoConfig;
    private final DaoConfig sportsBeanDaoConfig;

    private final UserBeanDao userBeanDao;
    private final ShareBeanDao shareBeanDao;
    private final SportsBeanDao sportsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        shareBeanDaoConfig = daoConfigMap.get(ShareBeanDao.class).clone();
        shareBeanDaoConfig.initIdentityScope(type);

        sportsBeanDaoConfig = daoConfigMap.get(SportsBeanDao.class).clone();
        sportsBeanDaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        shareBeanDao = new ShareBeanDao(shareBeanDaoConfig, this);
        sportsBeanDao = new SportsBeanDao(sportsBeanDaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(ShareBean.class, shareBeanDao);
        registerDao(SportsBean.class, sportsBeanDao);
    }
    
    public void clear() {
        userBeanDaoConfig.clearIdentityScope();
        shareBeanDaoConfig.clearIdentityScope();
        sportsBeanDaoConfig.clearIdentityScope();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public ShareBeanDao getShareBeanDao() {
        return shareBeanDao;
    }

    public SportsBeanDao getSportsBeanDao() {
        return sportsBeanDao;
    }

}
